"""
Django settings for hpmaharaja project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in the Vercel project's environment variables.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    'django-insecure-k+574q#u$326f&_!9u3zfz7=n)yt!00%(74x*=sjxoy&esjtl_',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Vercel always sets VERCEL=1, so deploys default to DEBUG off while local
# runserver stays on. DJANGO_DEBUG=1 / 0 overrides either way.
DEBUG = os.environ.get("DJANGO_DEBUG", "0" if os.environ.get("VERCEL") else "1") == "1"


ALLOWED_HOSTS = [
    ".vercel.app",        # Vercel’s domain
    "localhost",
    "127.0.0.1",
    # add your custom domain here when you connect one, e.g.:
    "hpmaharaja.com",
    "www.hpmaharaja.com",
    "heranpatel.com",
    "www.heranpatel.com"
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.vercel.app",
    "https://hpmaharaja.com",
    "https://www.hpmaharaja.com",
    "https://heranpatel.com",
    "https://www.heranpatel.com",
]

if not DEBUG:
    # Vercel terminates TLS at its proxy and forwards this header.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # On Vercel static files are served from the CDN and this is inert; it is
    # what serves them under `vercel dev` and any non-Vercel host.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hpmaharaja.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hpmaharaja.wsgi.application'

# Vercel resolves the serverless entrypoint from these two settings, preferring
# ASGI when both are present. Without it, hpmaharaja/asgi.py is never used.
ASGI_APPLICATION = 'hpmaharaja.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.dummy",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "America/Los_Angeles"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',   # we’ll create static/ in root
]
# Required for Vercel to run collectstatic during the build and serve the
# result from its CDN at STATIC_URL.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django 5.1 removed the STATICFILES_STORAGE setting this project used to set,
# so that line was silently doing nothing; STORAGES replaces it.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

